var namespace_finament_1_1_application_1_1_d_t_os_1_1_users_1_1_requests =
[
    [ "CreateUserDto", "class_finament_1_1_application_1_1_d_t_os_1_1_users_1_1_requests_1_1_create_user_dto.html", "class_finament_1_1_application_1_1_d_t_os_1_1_users_1_1_requests_1_1_create_user_dto" ],
    [ "UpdateUserDto", "class_finament_1_1_application_1_1_d_t_os_1_1_users_1_1_requests_1_1_update_user_dto.html", "class_finament_1_1_application_1_1_d_t_os_1_1_users_1_1_requests_1_1_update_user_dto" ]
];